spring:
    datasource:
        min-idle: 5
        test-while-idle: true
        time-between-eviction-runs-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        max-wait: 60000
        url: jdbc:mysql://172.16.225.9:3306/sop_business?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
        max-idle: 10
        username: root
        password: sd_test_mysql_1q2w3e

        test-on-borrow: true
        min-evictable-idle-time-millis: 1800000
        initial-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        test-on-return: false

server:
port: 9010